version: '3.3'

services:

  web:
    build:
      context: ./
      args:
        VHOST: ${VIRTUAL_HOST}
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    depends_on:
      - db
    networks:
      - default
      - nginx_proxy

  db:
    build: ./docker/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - default
      - databases

  ## Adminer MySQL admin interface, at localhost:3001

  # admininastror:
  #   image: adminer
  #   ports:
  #     - "3001:8080"
  #   environment:
  #     ADMINER_DESIGN: pepa-linha

  ## Nginx reverse proxy, sends VIRTUAL_HOST requests to port 80
  #  run if you don't have one already on
  #  see README for details

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  ## Joins the network of an existing nginx reverse proxy
  #  see README for details
  nginx_proxy:
    external:
      name: nginx_proxy
  databases:
    external:
      name: databases
