version: '3.3'

services:

  web:
    build: nginx
    # image: webdevops/php-nginx:alpine-php7
    volumes:
      - type: bind
        source: ./../
        target: /app
      - type: bind
        source: ./nginx/vhost.conf
        target: /opt/docker/etc/nginx/vhost.conf
    environment:
      VIRTUAL_HOST: memuller.test,jeancatanho.test
    networks:
      - default
      - nginx_proxy

  db:
    build: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: memuller
    # volumes:
    #   - ./share/mysql:/docker-entrypoint-initdb.d
    networks:
      - default
      - databases

  ## Adminer MySQL admin interface, at localhost:3001
  
  # admininastror:
  #   image: adminer
  #   ports:
  #     - "3001:8080"
  #   environment:
  #     ADMINER_DESIGN: pepa-linha

  ## Nginx reverse proxy, sends memuller.test to port 80
  #  run if you don't have one already on
  #  see README for details
  
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  ## Joins the network of an existing nginx reverse proxy
  #  see README for details
  nginx_proxy:
    external:
      name: nginx_proxy
  databases:
    external:
      name: databases